config/routes.rb
Rails.application.routes.draw do
  resources :books
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
  end
  def new
      @book = Book.new
    end
  def create
      @book = Book.new(book_params)

      if @book.save
        redirect_to books_path, notice: "新增書本成功!"
      else
        render :new
      end
  end
  def edit
      @book = Book.find_by(id: params[:id])
  end
  def update
      @book = Book.find_by(id: params[:id])

      if @book.update(book_params)
        # 成功
        redirect_to books_path, notice: "資料更新成功!"
      else
        # 失敗
        render :edit
      end
  end
  def destroy
      @book = Book.find_by(id: params[:id])
      @book.destroy if @book
      redirect_to books_path, notice: "書本資料已刪除!"
  end
  def show
    @book = Book.find_by(id: params[:id])
  end
  private
    def book_params
      params.require(:book).permit(:bookname, :introduction, :authorname, :price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
    <%= f.label :bookname, "書名" %>
    <%= f.text_field :bookname %> <br />

    <%= f.label :introduction, "簡介" %>
    <%= f.text_field :introduction %> <br />

    <%= f.label :authorname, "作者姓名" %>
    <%= f.text_field :authorname %> <br />

    <%= f.label :price, "售價" %>
    <%= f.text_area :price %> <br />

    <%= f.submit %>
  <% end %>

app/views/books/edit.html.erb
  <h1>新增書本</h1>
  <%= render "form", book: @book %>
  

  <br />
  <%= link_to '回書本列表', books_path %>

app/views/books/index.html.erb
<h1>書本列表</h1>

  <%= link_to "新增書本", new_book_path %>

  <table>
    <thead>
      <tr>
        <td>書名</td>
        <td>簡介</td>
        <td>作者姓名</td>
        <td>售價</td>
      </tr>
    </thead>
    <tbody>
      <% @books.each do |book| %>
      <tr>
        <td><%= link_to book.bookname , book %></td>
<!--         <td><%= book.bookname %></td> -->
        <td><%= book.introduction %></td>
        <td><%= book.authorname %></td>
        <td><%= book.price %></td>
        <td>
          <%= link_to "編輯", edit_book_path(book) %>
          <%= link_to "刪除", book_path(book), method: "delete", data: { confirm: "確認刪除" } %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>

app/views/books/new.html.erb
  <h1>新增書本</h1>

  <%= form_for(@book) do |f| %>
    <%= f.label :bookname, "書名" %>
    <%= f.text_field :bookname %> <br />

    <%= f.label :introduction, "簡介" %>
    <%= f.text_field :introduction %> <br />

    <%= f.label :authorname, "作者姓名" %>
    <%= f.text_field :authorname %> <br />

    <%= f.label :price, "售價" %>
    <%= f.text_area :price %> <br />

    <%= f.submit %>
  <% end %>

  <br />
  <%= link_to '回書本列表', books_path %>

app/views/books/show.html.erb
<h1><%= @book.bookname %></h1>

introduction: <%= @book.introduction %>
<br />
authorname: <%= @book.authorname %>
<br />
price: <%= @book.price %>
<br />

<%= link_to "back" , books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Librarymanager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>